import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { JsonLd } from "@/components/JsonLd";
import { SITE_URL, keywords, person } from "@/constants/profile";

/**
 * The reference build runs on exactly two families: Bricolage Grotesque for
 * every headline and Inter for every word a human has to read. Both are
 * variable, so one file per family covers the whole weight range.
 */
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["400", "500"],
});

const TITLE = `${person.name} (${person.handle}), Generative AI Engineer`;
// Kept under ~160 characters so Google shows it whole instead of truncating.
const DESCRIPTION =
  "Ashutosh Kumar (ashusnapx), Generative AI Engineer. I build production LLM apps: RAG pipelines, multi-agent workflows, and the products they ship inside.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: TITLE, template: `%s | ${person.name}` },
  description: DESCRIPTION,
  keywords,
  applicationName: `${person.name} Portfolio`,
  authors: [{ name: person.name, url: SITE_URL }],
  creator: person.name,
  publisher: person.name,
  category: "technology",
  alternates: { canonical: "/" },
  // Generated by Next from icon.png / apple-icon.png in app/, both cropped
  // from the headshot. Declared explicitly so the 96px PNG is what Google
  // picks up for the SERP favicon.
  icons: {
    icon: [{ url: "/icon.png", type: "image/png", sizes: "96x96" }],
    apple: "/apple-icon.png",
  },
  openGraph: {
    type: "profile",
    url: SITE_URL,
    siteName: `${person.name}, ${person.role}`,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    firstName: "Ashutosh",
    lastName: "Kumar",
    username: person.handle,
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${person.name}, Generative AI Engineer`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    creator: `@${person.handle}`,
    site: `@${person.handle}`,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.webmanifest",
  // Fill these in from Search Console and Bing Webmaster Tools. Verification
  // is what unlocks indexing reports and the URL inspection tool.
  // verification: { google: "…", other: { "msvalidate.01": "…" } },
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <JsonLd />
      </head>
      <body
        className={`${bricolage.variable} ${inter.variable} ${jetbrains.variable} relative min-h-[100dvh] overflow-x-hidden font-sans text-ink antialiased`}
      >
        {/* One gradient behind the whole document: day at the top,
            dusk by the footer. */}
        <div className="daynight" aria-hidden />
        {children}
      </body>
    </html>
  );
}
